services:
  postgres:
    container_name: chat_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: next_chat
      POSTGRES_PASSWORD: pass_next_chat_word
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend_network


volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
